[basic-information]
name = "1x1x2" # may be extended later
version = 1
type = "puzzle"

[positions]
positions = [ [1,1] , [2,2] , [3,3] , [4,4] , [5,5], [6,2] , [7,3] , [8,4] , [9,5] , [10,6] ]

[moves] 
u = [ [2,3] , [3,4] , [4,5] , [5,2] , [1,1] , [10,10] , [6,6] , [7,7] , [8,8] , [9,9] ]
up = [ [2,5] , [3,2] , [4,3] , [5,4] , [1,1] , [10,10] , [6,6] , [7,7] , [8,8] , [9,9] ]
d = [ [6,9] , [7,6] , [8,7] , [9,8] , [1,1] , [10,10] , [1,1] , [2,2] , [3,3] , [4,4] ]
dp = [ [6,7] , [7,8] , [8,9] , [9,6] , [1,1] , [10,10] , [1,1] , [2,2] , [3,3] , [4,4] ]
